version: 2

models:
  - name: stg_local_bike_operational_database__brands
    description: "This model contains information about brands."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
            - unique
            - not_null
      - name: brand_name
        description: "Name of the brand"
  - name: stg_local_bike_operational_database__categories
    description: "This model contains information about product categories."
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each product category."
        tests:
            - unique
            - not_null
      - name: category_name
        data_type: string
        description: "Name of the product category."
  - name: stg_local_bike_operational_database__customers
    description: "This model contains information about customers."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null

      - name: first_name
        data_type: string
        description: "Customer's first name."

      - name: last_name
        data_type: string
        description: "Customer's last name."

      - name: phone
        data_type: string
        description: "Customer's phone number."

      - name: email
        data_type: string
        description: "Customer's email address."

      - name: street
        data_type: string
        description: "Customer's street address."

      - name: city
        data_type: string
        description: "Customer's city."

      - name: state
        data_type: string
        description: "Customer's state or region."

      - name: zip_code
        data_type: int64
        description: "Customer's postal / ZIP code."

  - name: stg_local_bike_operational_database__order_items
    description: "This model contains information about each item included in an order, including its unit price, quantity and discount."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item. "
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike_operational_database__order_item
              arguments:
                to: ref('stg_local_bike_operational_database__orders')
                field: order_id
      - name: product_id
        description: "Foreign key linking the order item to the corresponding product."
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_local_bike_operational_database__order_item
              arguments:
                to: ref('stg_local_bike_operational_database__products')
                field: product_id

      - name: quantity
        data_type: int64
        description: "Quantity of the product ordered."

      - name: list_price
        data_type: float64
        description: "List price of the product at the time of the order."

      - name: discount
        data_type: float64
        description: "Discount applied to the product at the time of the order."
      # - name: total_order_item_amount
      #   description: "Total order item amount calculated with quantity * list_price with applied discount."
  - name: stg_local_bike_operational_database__orders
    description: "This model contains information about orders placed by customers, including the order status, the store where the order has been made and the staff who took care of the order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      # - name: order_status
      #   description: "Foreign key to status table." # No status table at the moment
      #   tests:
      #     - not null
      #     - relationships:
      #         name: user_id_foreign_key_in_stg_local_bike_operational_database__orders
      #         arguments:
      #           to: ref('stg_local_bike_operational_database__customers')
      #           field: customer_id
      - name: customer_id
        description: "Foreign key linking the order to the customer who placed it."
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_local_bike_operational_database__orders
              arguments:
                to: ref('stg_local_bike_operational_database__customers')
                field: customer_id
      - name: store_id
        description: "Foreign key linking the order to the customer who placed it."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_local_bike_operational_database__orders
              arguments:
                to: ref('stg_local_bike_operational_database__stores')
                field: store_id
      - name: staff_id
        description: "Foreign key linking the order to the customer who placed it."
        tests:
          - relationships:
              name: staff_id_foreign_key_in_stg_local_bike_operational_database__orders
              arguments:
                to: ref('stg_local_bike_operational_database__staffs')
                field: staff_id
      
      - name: order_status
        data_type: int64
        description: "Status of the order: undocumented codes."

      - name: order_date
        data_type: date
        description: "Date when the order was placed."

      - name: required_date
        data_type: date
        description: "Date when the order is required."

      - name: shipped_date
        data_type: date
        description: "Date when the order was shipped."

  - name: stg_local_bike_operational_database__products
    description: "This model contains information about products."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null

      - name: product_name
        data_type: string
        description: "Name of the product."

      - name: brand_id
        data_type: int64
        description: "Foreign key to the brand table."

      - name: category_id
        data_type: int64
        description: "Foreign key to the category table."

      - name: model_year
        data_type: int64
        description: "Model year of the product."

      - name: list_price
        data_type: float64
        description: "List price of the product."

  - name: stg_local_bike_operational_database__staffs
    description: "This model contains information about staff members."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff member."
        tests:
            - unique
            - not_null
      - name: manager_id
        description: "Foreign key pointing to the staff member's manager."
        # tests:
        #   - relationships: # Problem : how to handle staff without manager ?
        #       name: manager_id_foreign_key_in_stg_local_bike_operational_database__staffs
        #       arguments:
        #         to: ref('stg_local_bike_operational_database__staffs')
        #         field: staff_id
      - name: store_id
        description: "Foreign key pointing to the staff member's store."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_local_bike_operational_database__staffs
              arguments:
                to: ref('stg_local_bike_operational_database__stores')
                field: store_id

      - name: first_name
        data_type: string
        description: "First name of the staff member."

      - name: last_name
        data_type: string
        description: "Last name of the staff member."

      - name: email
        data_type: string
        description: "Email address of the staff member."

      - name: phone
        data_type: string
        description: "Phone number of the staff member."

      - name: active
        data_type: int64
        description: "Indicates if the staff member is currently active."

  - name: stg_local_bike_operational_database__stocks
    description: "This model contains information about stocks per product per store."
    columns:
      - name: store_id
        description: "Foreign key to the store table."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_local_bike_operational_database__stocks
              arguments:
                to: ref('stg_local_bike_operational_database__stores')
                field: store_id
      - name: product_id
        description: "Foreign key to the product table."
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_local_bike_operational_database__stocks
              arguments:
                to: ref('stg_local_bike_operational_database__products')
                field: product_id
      - name: quantity
        description: "Quantity of the product available in stock at the store."

  - name: stg_local_bike_operational_database__stores
    description: "This model contains information about stores."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
            - unique
            - not_null

      - name: store_name
        data_type: string
        description: "Name of the store."

      - name: phone
        data_type: string
        description: "Phone number of the store."
        
      - name: email
        data_type: string
        description: "Email address of the store."

      - name: street
        data_type: string
        description: "Street address of the store."

      - name: city
        data_type: string
        description: "City of the store."

      - name: state
        data_type: string
        description: "State of the store."

      - name: zip_code
        data_type: int64
        description: "Zip code of the store."